disabled_rules:
  - trailing_whitespace
  - todo
  - attributes
  - void_function_in_ternary

included:
  - KPIHubIOS

excluded:
  - Carthage
  - Pods
  - KPIHubIOS/Resources

opt_in_rules:
  - closure_end_indentation
  - conditional_returns_on_newline
  - explicit_init
  - fatal_error_message
  - first_where
  - operator_usage_whitespace
  - vertical_parameter_alignment_on_call
  - switch_case_on_newline
  - closure_spacing
  - discouraged_direct_init
  - unneeded_parentheses_in_closure_argument
  - nesting
  - nimble_operator
  - implicit_return
  - empty_string
  - shorthand_optional_binding
  - direct_return
  - anonymous_argument_in_multiline_closure
  - let_var_whitespace
  - untyped_error_in_catch
  - multiline_arguments_brackets
  - discouraged_none_name
  - redundant_type_annotation
  - vertical_whitespace
  - for_where
  - unavailable_function
  - object_literal
  - lower_acl_than_parent
  - reduce_into
  - contains_over_filter_is_empty
  - return_value_from_void_function
  - private_subject
  - contains_over_first_not_nil
  - modifier_order
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - duplicate_enum_cases
  - toggle_bool
  - prefer_self_type_over_type_of_self
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - last_where
  - indentation_width
  - colon
  - redundant_nil_coalescing


force_cast: warning
force_try:
  severity: warning
line_length: 180

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 10

type_name:
  min_length: 2
  max_length:
    warning: 50

identifier_name:
  min_length:
    warning: 2

vertical_whitespace:
  max_empty_lines: 2

  excluded:
  - id
  - ID
  - URL
  - iv
  - cc
  - ad
  - up
  - preferredInterfaceOrientationForPresentation

closure_end_indentation: error
fatal_error_message: error
vertical_parameter_alignment_on_call: warning
switch_case_on_newline: warning

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
